### ISSUE TITLE
Jukebox only have one song

### ISSUE THREAD

**Issue by yanhengxu98** [decentraland-scenes/Awesome-Repository#7]
![image](https://user-images.githubusercontent.com/48979618/147407760-afc1134f-09a0-4f3d-8a29-1bfbbcd9c00c.png)
Like this, I tested by changing iterators in for loop, and found the for loop has only been triggered for ones. 
Which is, if I change the initial value of i, the only appeared song will be the 2nd, 3rd, or 4th.
I am not so familiar with JS, so could you please check and help? thanks.

**Comment by nearnshaw** [comment]
Thanks @yanhengxu98 
There was a bug with the scene's code, I just pushed a fix. It should now have 4 buttons and work as expected
