### ISSUE TITLE
Avocado does not appear in Decentraland SDK

### ISSUE THREAD

**Issue by rmayer78** [decentraland-scenes/Awesome-Repository#9]
I've copied the code exactly as it is on here into Visual Studio and the decentraland scene preview won't add it. Is there anything that commonly may cause this issue?

Thanks

**Comment by nearnshaw** [comment]
The Avocado and any associated texture or related file must be added as a file within the project folder. Copying the code alone will not include a reference to the 3d model if it's not in the project and in the same relative folder as used in the example.

For help debugging your issue, please reach out to the Decentraland Discord SDK channel, where other developers are sure to be able to help you out
